Get FishNet running
hyperledger/sawtooth-supply-chain pull request #6
Opened 2017-10-12 18:16 UTC by delventhalz

With the changes in this PR, you should be able to run FishNet. This does not update `run_tests`, `run_docker_tests`, `run_lint`, or `run_bandit`. The deployment process will also be streamlined in future PRs.

To run, download the repo, and from the project directory:
```bash
docker-compose up
```

Then in a new process:
```bash
./bin/protogen
docker exec -it sawtooth-client-default bash
```

This will enter the sawtooth client container which has the `sawtooth_sdk` in the PYTHONPATH, which the transaction processor needs. So from within that container:
```bash
cd sawtooth-supply-chain/
./bin/transaction-processor
```

Open one more process:
```bash
cd client/
npm install
npm run build
cd ../server/
npm install
npm run init
npm run make-fish
curl localhost:8008/batches -X POST -H "Content-Type: application/octet-stream" --data-binary @fish.batch 
npm start
```

Now you should be able to navigate to `http://localhost:3000/fish` and see the FishNet client. Creating users, fish, and updating data should all work.

2017-10-13 15:11 UTC, peterschwarz requested changes

2017-10-13 15:11 UTC, peterschwarz commented on client/src/services/api.js
> +const STORAGE_KEY = 'fishnet.authorization'
This should be `supply_chain`

2017-10-13 15:11 UTC, peterschwarz commented on client/src/services/transactions.js
> +const STORAGE_KEY = 'fishnet.encryptedKey'
ditto

2017-10-13 15:11 UTC, peterschwarz commented on docs/source/family_specification.rst
>     >>> get_hash('track_and_trade')[:6]
Should this get updated to `supply_chain`?  If not, perhaps this should be noted that it is `track_and_trade`, for historical reasons.

2017-10-13 15:11 UTC, peterschwarz commented on server/db/index.js
> +const NAME = process.env.DB_NAME || 'sc'
This should be the full word for the db name: `supply_chain`, no reason this should be short - it's not informative enough.

2017-10-13 15:11 UTC, peterschwarz commented on server/scripts/bootstrap_database.js
> +const NAME = process.env.DB_NAME || 'sc'
`supply_chain`

2017-10-13 15:51 UTC, delventhalz commented on client/src/services/api.js
> +const STORAGE_KEY = 'fishnet.authorization'
It's part of the client, with runs on Sawtooth Supply Chain, but there could be than one client per Supply Chain server. So `fish_net.authorization`, `asset_track.authorization`, etc. I am feeling the underscores though . . .

2017-10-13 18:20 UTC, peterschwarz commented on client/src/services/api.js
> +const STORAGE_KEY = 'fishnet.authorization'
Ah, I see.  This is the storage key in `localStorage`.

2017-10-13 18:22 UTC, peterschwarz approved these changes

2017-10-14 14:26 UTC, vaporos commented
We should use supply-chain-tp or sawtooth-supply-chain-tp as the script name, for a couple reasons:

a) will make more sense in "ps" output
b) approach is compatible with projects with more than one transaction processor, for which this might serve as an example

2017-10-14 14:28 UTC, vaporos approved these changes

2017-10-14 15:36 UTC, delventhalz commented
Renamed to `supply_chain_tp`. Though I wonder now if the abbreviation "tp" is clear enough. Maybe "supply_chain_processor" would be more appropriate. In any case, merging it as is. Names can be nailed down later.

2017-10-14 15:36 UTC, merged